import React from 'react';
import { Button, Space, Typography } from "antd";
const { Text } = Typography;

interface SecondProps {
    instantiateEscrow: () => void;
}

const Second: React.FC<SecondProps> = ({instantiateEscrow}) => {

    return (
        <Space direction="vertical" style={{ width: "100%", alignItems: "center" }}>
            <Text>
                Now, create an escrow account to receive incoming funds generated by your predictable revenue stream.
            </Text>
            <Button
                type="primary"
                size="large"
                onClick={instantiateEscrow}
                style={{
                    borderRadius: 8,
                    // backgroundColor: "#1677ff",
                    // color: "white",
                    minWidth: 150,
                }}
            >
                Create Escrow Account
            </Button>
        </Space>
    );
};

export default Second;
