export const exampleBonds = [
    {
        id: 1,
        name: "Bond A",
        description: "Invest in DAO project",
        yield: "5% per year",
        maturity: "12 months",
        total: "100",
        available: "40",
        iHave: "0",
        pricePerBond: "1000",
        tokenPerBond: "5",
    },
    {
        id: 2,
        name: "Bond B",
        description: "Invest in DAO project",
        yield: "7% per year",
        maturity: "18 months",
        total: "100",
        available: "40",
        iHave: "0",
        pricePerBond: "1000",
        tokenPerBond: "5",
    },
    {
        id: 3,
        name: "Bond C",
        description: "Infrastructure development",
        yield: "6% per year",
        maturity: "24 months",
        total: "100",
        available: "40",
        iHave: "0",
        pricePerBond: "1000",
        tokenPerBond: "5",
    },
    {
        id: 4,
        name: "Bond D",
        description: "Invest in DAO project",
        yield: "5% per year",
        maturity: "12 months",
        total: "100",
        available: "40",
        iHave: "0",
        pricePerBond: "1000",
        tokenPerBond: "5",
    },
    {
        id: 5,
        name: "Bond E",
        description: "Invest in DAO project",
        yield: "7% per year",
        maturity: "18 months",
        total: "100",
        available: "40",
        iHave: "0",
        pricePerBond: "1000",
        tokenPerBond: "5",
    },
    {
        id: 6,
        name: "Bond F",
        description: "Infrastructure development",
        yield: "6% per year",
        maturity: "24 months",
        total: "100",
        available: "40",
        iHave: "0",
        pricePerBond: "1000",
        tokenPerBond: "5",
    },
];